// frontend/app/components/layout/AffiliateSidebar.vue
<template>
  <aside class="affiliate-sidebar">
    <div class="affiliate-badge">
      <span>Afiliado</span>
      <strong>Nível Ouro</strong>
    </div>

    <nav class="affiliate-nav">
      <NuxtLink v-for="item in navItems" :key="item.to" :to="item.to" class="nav-link" :class="{ active: isActive(item.to) }">
        <component :is="item.icon" :size="16" />
        {{ item.label }}
      </NuxtLink>
    </nav>

    <div class="affiliate-footer">
      <NuxtLink to="/account" class="nav-link" :class="{ active: route.path === '/account' }"><User :size="15" /> Account</NuxtLink>
      <NuxtLink to="/logout" class="nav-link"><LogOut :size="15" /> Logout</NuxtLink>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { FileImage, LayoutDashboard, Link2, LogOut, Receipt, User, Users, Wallet } from 'lucide-vue-next'

const route = useRoute()
const navItems = [
  { icon: LayoutDashboard, label: 'Dashboard', to: '/afiliados' },
  { icon: Link2, label: 'Meu link', to: '/afiliados/meu-link' },
  { icon: Receipt, label: 'Extrato', to: '/afiliados/extrato' },
  { icon: Users, label: 'Indicados', to: '/afiliados/indicados' },
  { icon: Wallet, label: 'Solicitar saque', to: '/afiliados/solicitar-saque' },
  { icon: FileImage, label: 'Material de divulgação', to: '/afiliados/material' },
]

const isActive = (path: string) => (path === '/afiliados' ? route.path === path : route.path.startsWith(path))
</script>

<style scoped>
.affiliate-sidebar {
  display: flex;
  flex-direction: column;
  width: 280px;
  height: calc(100vh - 56px);
  flex: 0 0 auto;
  border-right: 1px solid rgba(255, 255, 255, 0.05);
  background: var(--surface);
}

.affiliate-badge {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 20px 16px;
}

.affiliate-badge span {
  color: var(--accent);
  font-size: 11px;
  font-weight: 800;
  letter-spacing: 0.6px;
  text-transform: uppercase;
}

.affiliate-badge strong {
  color: var(--muted);
  font-size: 12px;
}

.affiliate-nav {
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 4px;
  padding: 12px;
  border-top: 1px solid rgba(255, 255, 255, 0.05);
}

.affiliate-footer {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px;
  border-top: 1px solid rgba(255, 255, 255, 0.05);
}

.nav-link {
  display: flex;
  align-items: center;
  gap: 12px;
  height: 40px;
  padding: 0 12px;
  border-radius: 4px;
  color: var(--muted-2);
  text-decoration: none;
  font-size: 14px;
  font-weight: 500;
}

.nav-link:hover {
  color: #fff;
}

.nav-link.active {
  background: var(--accent);
  color: var(--bg);
  font-weight: 800;
}

@media (max-width: 900px) {
  .affiliate-sidebar {
    display: none;
  }
}
</style>

// oddfix-frontend/src/app/components/layout/AffiliateSidebar.tsx
import type { ReactNode } from "react";
import { Link, useLocation } from "react-router";
import {
  LayoutDashboard,
  Link2,
  Receipt,
  Users,
  Wallet,
  FileImage,
  User,
  LogOut,
} from "lucide-react";

const NAV_ITEMS = [
  { icon: <LayoutDashboard size={16} />, label: "Dashboard", to: "/afiliados" },
  { icon: <Link2 size={16} />, label: "Meu link", to: "/afiliados/meu-link" },
  { icon: <Receipt size={16} />, label: "Extrato", to: "/afiliados/extrato" },
  { icon: <Users size={16} />, label: "Indicados", to: "/afiliados/indicados" },
  { icon: <Wallet size={16} />, label: "Solicitar saque", to: "/afiliados/solicitar-saque" },
  { icon: <FileImage size={16} />, label: "Material de divulgação", to: "/afiliados/material" },
];

export function AffiliateSidebar() {
  const { pathname } = useLocation();

  return (
    <aside
      className="hidden md:flex flex-col shrink-0"
      style={{
        width: "280px",
        backgroundColor: "#15181e",
        borderRight: "1px solid rgba(255,255,255,0.05)",
        height: "calc(100vh - 56px)",
      }}
    >
      {/* Level badge */}
      <div className="flex flex-col gap-3 px-4 py-5">
        <div className="flex flex-col gap-0.5">
          <span
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "11px",
              fontWeight: 700,
              color: "#8bf2c1",
              letterSpacing: "0.6px",
              textTransform: "uppercase",
            }}
          >
            Afiliado
          </span>
          <span
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: "12px",
              fontWeight: 500,
              color: "#71717a",
            }}
          >
            Nível Ouro
          </span>
        </div>
      </div>

      <div style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }} />

      {/* Nav items */}
      <nav className="flex flex-col gap-1 px-3 py-3 flex-1">
        {NAV_ITEMS.map(({ icon, label, to }) => {
          const isActive = to === "/afiliados" ? pathname === "/afiliados" : pathname.startsWith(to);
          return (
            <NavItem key={to} icon={icon} label={label} to={to} isActive={isActive} />
          );
        })}
      </nav>

      {/* Footer */}
      <div
        className="flex flex-col gap-1 px-3 py-3"
        style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}
      >
        <NavItem icon={<User size={15} />} label="Account" to="/account" isActive={pathname === "/account"} />
        <NavItem icon={<LogOut size={15} />} label="Logout" to="/logout" isActive={false} />
      </div>
    </aside>
  );
}

function NavItem({
  icon,
  label,
  to,
  isActive,
}: {
  icon: ReactNode;
  label: string;
  to: string;
  isActive: boolean;
}) {
  return (
    <Link
      to={to}
      className="flex items-center gap-3 px-3 rounded"
      style={{
        height: "40px",
        backgroundColor: isActive ? "#8bf2c1" : "transparent",
        color: isActive ? "#080b0f" : "#a1a1aa",
        fontFamily: "Inter, sans-serif",
        fontSize: "14px",
        fontWeight: isActive ? 700 : 500,
        textDecoration: "none",
        borderRadius: "4px",
        transition: "background-color 0.15s, color 0.15s",
      }}
      onMouseEnter={(e) => {
        if (!isActive) {
          e.currentTarget.style.color = "#ffffff";
        }
      }}
      onMouseLeave={(e) => {
        if (!isActive) {
          e.currentTarget.style.color = "#a1a1aa";
        }
      }}
    >
      {icon}
      {label}
    </Link>
  );
}
